[project]
authors = ["Ryan Oates <ryanoatsie@outlook.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-academic-research-system"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.4.0.dev2025061205,<26"
anthropic = ">=0.54.0,<0.55"
openai = ">=1.86.0,<2"
pip = ">=25.1.1,<26"
